# Generated by Django 3.1.7 on 2021-03-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=9)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policyNumber', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('typeOfPolicy', models.CharField(choices=[('PT1', 'Policy Type 1'), ('PT2', 'Policy Type 2')], max_length=3)),
                ('effectiveDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='INDIVIDUAL_FIRST_NAME')),
                ('lastName', models.CharField(max_length=50, verbose_name='INDIVIDUAL_LAST_NAME')),
                ('email', models.CharField(max_length=120, verbose_name='INDIVIDUAL_EMAIL')),
                ('phoneNumber', models.CharField(max_length=10, verbose_name='INDIVIDUAL_PHONE_NUMBER')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='INDIVIDUAL_ADDRESS', to='clients.address')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='INDIVIDUAL_POLICY', to='clients.address')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCompany', models.CharField(max_length=50, verbose_name='COMPANY_NAME')),
                ('email', models.CharField(max_length=120, verbose_name='EMAIL')),
                ('phoneNumber', models.CharField(max_length=10, verbose_name='COMPANY_PHONE_NUMBER')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='COMPANY_ADDRESS', to='clients.address')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='COMPANY_POLICY', to='clients.address')),
            ],
        ),
    ]
