# Generated by Django 3.1.7 on 2021-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210309_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='id',
        ),
        migrations.AddField(
            model_name='individual',
            name='licenseNumber',
            field=models.CharField(default='000000', max_length=30, primary_key=True, serialize=False),
        ),
    ]
